services:
  postgres:
    image: postgres:latest
    container_name: authdb
    environment:
      POSTGRES_PASSWORD: unicorn
      POSTGRES_DB: authentication
    ports:
      - "5432:54232"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  spring-boot-app:
    image: jelastic/maven:3.9.9-temurinjdk-21.0.2-almalinux-9
    container_name: spring-app
    #Repostirory wird geklont, maven compiled zu jar und jar ausgeführt
    command: >
      sh -c "git clone https://github.com/TGM-HIT/syt5-gek961-cloud-datenmanagement-ahuja_princ.git && cd syt5-gek961-cloud-datenmanagement-ahuja_princ && mvn clean install && cd target && java -jar GK961-0.0.1-SNAPSHOT.jar"  # Adjust as necessary
    depends_on:
      - postgres