services:
  postgres:
    image: postgres:latest
    container_name: authdb
    environment:
      POSTGRES_PASSWORD: unicorn
      POSTGRES_DB: authentication
    ports:
      - "5432:54232"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
